services:
  agent:
    build: 
      context: .
      dockerfile: Dockerfile
    image: wisrovi/agents:gpu-slim
    
  dvc:
    build: 
      context: extra_images
      dockerfile: Dockerfile.dvc
    image: wisrovi/agents:gpu-slim-dvc
    depends_on:
      - agent
  
  yolo:
    build: 
      context: extra_images
      dockerfile: Dockerfile.yolo
    image: wisrovi/agents:gpu-slim-yolo
    depends_on:
      - agent
  
  complete:
    build: 
      context: extra_images
      dockerfile: Dockerfile.complete
    image: wisrovi/agents:gpu
    depends_on:
      - agent
